default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["MYSQL_USER"] %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
  port: 3306
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: prod
  username: production
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
